Put modify
Takzzg/FoodFast-Client pull request #3
Opened 2022-06-16 19:09 UTC by CarlosG1272

1. Añadí las respectivas funciones y configuraciones para guardar la imágen como codigo binario, ahora se guarda directamente en mongo y se renderiza sin problema alguno. 
![image](https://user-images.githubusercontent.com/98417965/174146087-570755d5-7a9e-4044-8ea3-2fbcd6c0f285.png)

2. Agregue confimación antes de borrar un producto y/o categoría 
![image](https://user-images.githubusercontent.com/98417965/174146319-b675cdf0-f0f0-47d0-bf4c-faf39c4abf27.png)
3. Añadí mensajes personalizables al momento de crear una categoria y producto
![image](https://user-images.githubusercontent.com/98417965/174146676-81149cfb-58be-495d-ab40-0e4a4c28e244.png)
![image](https://user-images.githubusercontent.com/98417965/174146703-888f54fc-5b95-4a9f-8a72-0a3d32990fd5.png)

4. Agregue las secciones de modificar tanto el producto y las categorías, siendo estas controladas y funcionales incluso cambiando la imagen. 
 
![image](https://user-images.githubusercontent.com/98417965/174146404-992e00df-6140-4fda-97c1-7f1904f2883b.png)
![image](https://user-images.githubusercontent.com/98417965/174146571-646b1bf7-eeb8-4ee9-8f59-c6a698036504.png)

PSDT: 
Las imágenes están vacias porque la carpeta de public ya no existe, y por tanto las imágenes almacenadas ahi ya no funcionan. PAra corregirlo solo tendriamos que usar la ruta de modificar y agregarle una nueva imagen
![image](https://user-images.githubusercontent.com/98417965/174146883-e30036eb-09f3-4515-8c88-a84723cb9840.png)

2022-06-16 19:38 UTC, Takzzg requested changes
- estas subiendo un .env, agregalo al gitignore.
- segun react, para limpiar un input, deberiamos ponerle como value un string vacio en vez de null (ej: CategoryForm/index.jsx - 24). fijate si te sigue diciendo eso en la consola

2022-06-16 20:43 UTC, foodFFast approved these changes

2022-06-16 21:00 UTC, foodFFast approved these changes

2022-06-17 00:32 UTC, Takzzg approved these changes

2022-06-17 00:33 UTC, merged